import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/MainLayout";
import MenuContextProvider from "@/context/MenuContext";


export const metadata: Metadata = {
  title: "Next Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MenuContextProvider>

          <MainLayout>
            {children}
          </MainLayout>
        </MenuContextProvider>
      </body>
    </html >
  );
}
